###
###
POST http://localhost:8080/student/add
Content-Type: application/json

{
  "firstname" :"souad",
  "lastname" :"slouma",
  "cin":"14214637",
  "adress":"sidi bouzid",
  "age":25,
  "universityuuid": "b2518933-ec83-49fc-9c31-890d930641f6"

}
###
POST http://localhost:8080/university/add
Content-Type: application/json

{
  "matricule":"mat-5048788563-880",
  "name" :"Espita",
  "location" :"Tunis",
  "dateCreation":"1996-04-11"

}
###

GET http://localhost:8080/university/getall
###
GET http://localhost:8080/student/getall
##
###
GET http://localhost:8080/student/findStudentByUniversity/b2518933-ec83-49fc-9c31-890d930641f6
##

